runmode: debug               # 开发模式, debug, release, test
addr: :8080                  # HTTP绑定端口
name: apiserver              # API Server的名字
url: http://127.0.0.1:8080   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数尝试的次数
log:
  logger_level: info
  logger_dir: log
  log_rotate_size: 1024
  log_backup_count: 30
  log_backup_days: 30
db:
  name: db_apiserver
  addr: 10.211.55.5:3306
  username: root
  password: cy.89757