// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProdModel struct {
	// @inject_tag:json:"id"
	ID int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"id"`
	// @inject_tag:json:"name"
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProdModel) Reset()         { *m = ProdModel{} }
func (m *ProdModel) String() string { return proto.CompactTextString(m) }
func (*ProdModel) ProtoMessage()    {}
func (*ProdModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}

func (m *ProdModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdModel.Unmarshal(m, b)
}
func (m *ProdModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdModel.Marshal(b, m, deterministic)
}
func (m *ProdModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdModel.Merge(m, src)
}
func (m *ProdModel) XXX_Size() int {
	return xxx_messageInfo_ProdModel.Size(m)
}
func (m *ProdModel) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdModel.DiscardUnknown(m)
}

var xxx_messageInfo_ProdModel proto.InternalMessageInfo

func (m *ProdModel) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ProdModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ProdsRequest struct {
	// @inject_tag:json:"size",form:"size"
	Size                 int32    `protobuf:"varint,1,opt,name=size,proto3" json:"size" form:"size"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProdsRequest) Reset()         { *m = ProdsRequest{} }
func (m *ProdsRequest) String() string { return proto.CompactTextString(m) }
func (*ProdsRequest) ProtoMessage()    {}
func (*ProdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{1}
}

func (m *ProdsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdsRequest.Unmarshal(m, b)
}
func (m *ProdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdsRequest.Marshal(b, m, deterministic)
}
func (m *ProdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdsRequest.Merge(m, src)
}
func (m *ProdsRequest) XXX_Size() int {
	return xxx_messageInfo_ProdsRequest.Size(m)
}
func (m *ProdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProdsRequest proto.InternalMessageInfo

func (m *ProdsRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type ProdDetailRequest struct {
	// @inject_tag:json:"id",form:"id",uri:"id"
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"id" form:"id" uri:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProdDetailRequest) Reset()         { *m = ProdDetailRequest{} }
func (m *ProdDetailRequest) String() string { return proto.CompactTextString(m) }
func (*ProdDetailRequest) ProtoMessage()    {}
func (*ProdDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{2}
}

func (m *ProdDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdDetailRequest.Unmarshal(m, b)
}
func (m *ProdDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdDetailRequest.Marshal(b, m, deterministic)
}
func (m *ProdDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdDetailRequest.Merge(m, src)
}
func (m *ProdDetailRequest) XXX_Size() int {
	return xxx_messageInfo_ProdDetailRequest.Size(m)
}
func (m *ProdDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProdDetailRequest proto.InternalMessageInfo

func (m *ProdDetailRequest) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type ProdDetailResponse struct {
	// @inject_tag:json:"data",form:"data"
	Data                 *ProdModel `protobuf:"bytes,1,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProdDetailResponse) Reset()         { *m = ProdDetailResponse{} }
func (m *ProdDetailResponse) String() string { return proto.CompactTextString(m) }
func (*ProdDetailResponse) ProtoMessage()    {}
func (*ProdDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{3}
}

func (m *ProdDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdDetailResponse.Unmarshal(m, b)
}
func (m *ProdDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdDetailResponse.Marshal(b, m, deterministic)
}
func (m *ProdDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdDetailResponse.Merge(m, src)
}
func (m *ProdDetailResponse) XXX_Size() int {
	return xxx_messageInfo_ProdDetailResponse.Size(m)
}
func (m *ProdDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProdDetailResponse proto.InternalMessageInfo

func (m *ProdDetailResponse) GetData() *ProdModel {
	if m != nil {
		return m.Data
	}
	return nil
}

type ProdListResponse struct {
	// @inject_tag:json:"data"
	Data                 []*ProdModel `protobuf:"bytes,1,rep,name=data,proto3" json:"data"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ProdListResponse) Reset()         { *m = ProdListResponse{} }
func (m *ProdListResponse) String() string { return proto.CompactTextString(m) }
func (*ProdListResponse) ProtoMessage()    {}
func (*ProdListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{4}
}

func (m *ProdListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdListResponse.Unmarshal(m, b)
}
func (m *ProdListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdListResponse.Marshal(b, m, deterministic)
}
func (m *ProdListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdListResponse.Merge(m, src)
}
func (m *ProdListResponse) XXX_Size() int {
	return xxx_messageInfo_ProdListResponse.Size(m)
}
func (m *ProdListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProdListResponse proto.InternalMessageInfo

func (m *ProdListResponse) GetData() []*ProdModel {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ProdModel)(nil), "protos.ProdModel")
	proto.RegisterType((*ProdsRequest)(nil), "protos.ProdsRequest")
	proto.RegisterType((*ProdDetailRequest)(nil), "protos.ProdDetailRequest")
	proto.RegisterType((*ProdDetailResponse)(nil), "protos.ProdDetailResponse")
	proto.RegisterType((*ProdListResponse)(nil), "protos.ProdListResponse")
}

func init() { proto.RegisterFile("product.proto", fileDescriptor_f0fd8b59378f44a5) }

var fileDescriptor_f0fd8b59378f44a5 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x28, 0xca, 0x4f,
	0x29, 0x4d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a, 0xfa,
	0x5c, 0x9c, 0x01, 0x45, 0xf9, 0x29, 0xbe, 0xf9, 0x29, 0xa9, 0x39, 0x42, 0x7c, 0x5c, 0x4c, 0x9e,
	0x2e, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x4c, 0x9e, 0x2e, 0x42, 0x42, 0x5c, 0x2c, 0x7e,
	0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x92, 0x12, 0x17, 0x0f,
	0x48, 0x43, 0x71, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x09, 0x48, 0x4d, 0x71, 0x66, 0x55, 0x2a,
	0x54, 0x17, 0x98, 0xad, 0xa4, 0xcc, 0x25, 0x08, 0x52, 0xe3, 0x92, 0x5a, 0x92, 0x98, 0x99, 0x03,
	0x53, 0x88, 0x66, 0xb8, 0x92, 0x35, 0x97, 0x10, 0xb2, 0xa2, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54,
	0x21, 0x55, 0x2e, 0x96, 0x94, 0xc4, 0x92, 0x44, 0xb0, 0x3a, 0x6e, 0x23, 0x41, 0x88, 0x6b, 0x8b,
	0xf5, 0xe0, 0x6e, 0x0c, 0x02, 0x4b, 0x2b, 0x59, 0x72, 0x09, 0x80, 0x84, 0x7c, 0x32, 0x8b, 0x4b,
	0xb0, 0x68, 0x65, 0xc6, 0xa3, 0xd5, 0x68, 0x36, 0x23, 0x17, 0x5f, 0x00, 0x24, 0x2c, 0x82, 0x53,
	0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0x3c, 0xb8, 0x78, 0xdd, 0x53, 0x4b, 0x10, 0xae, 0x11, 0x92,
	0x44, 0xd6, 0x8c, 0xe2, 0x0d, 0x29, 0x29, 0x6c, 0x52, 0x10, 0x17, 0x28, 0x31, 0x08, 0xd9, 0x73,
	0x71, 0x43, 0x4d, 0x02, 0x39, 0x4d, 0x48, 0x04, 0x59, 0x31, 0x2c, 0xc8, 0xa4, 0x24, 0x90, 0x45,
	0x91, 0xbd, 0xa0, 0xc4, 0x90, 0x04, 0x89, 0x17, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe2,
	0xfa, 0xec, 0x94, 0xaf, 0x01, 0x00, 0x00,
}
